name: BuildiOSOs6sg3fgsdgg

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest # MÃ¡quina macOS com Xcode
    steps:
    - uses: actions/checkout@v3
    - name: Install Fastlane
      run: gem install fastlane
    - name: Install Dependencies
      run: bundle install # Se usar Pods
    - name: Build iOS App (IPA)
      # Configurar chaves e certificados no GitHub Secrets
      run: fastlane build_app_ipa # Ou xcodebuild -workspace ... -scheme ... -configuration Release -destination generic/platform=iOS archive ... build -archivePath ... -exportPath ...
    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v3
      with:
        name: MyApp-iOS
        path: build/MyApp.ipa # Caminho para o IPA gerado
